
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COMMA DOT FUNCTION LBRACKET LPAREN NUMBER RBRACKET RPAREN STRING VARexpression : VAR DOT function_chainfunction_chain : function\n                        | function DOT function_chain\n    function : FUNCTION LPAREN params RPAREN params : param COMMA param\n                | param\n    atom : STRING\n            | NUMBER\n    list_elements : atom\n                    | atom COMMA list_elements\n                    | list_elements COMMA atom\n    list : LBRACKET list_elements RBRACKET param : list\n            | STRING\n            | NUMBER\n    '
    
_lr_action_items = {'VAR':([0,],[2,]),'$end':([1,4,5,9,16,],[0,-1,-2,-3,-4,]),'DOT':([2,5,16,],[3,7,-4,]),'FUNCTION':([3,7,],[6,6,]),'LPAREN':([6,],[8,]),'STRING':([8,15,17,24,25,],[13,20,13,20,20,]),'NUMBER':([8,15,17,24,25,],[14,21,14,21,21,]),'LBRACKET':([8,17,],[15,15,]),'RPAREN':([10,11,12,13,14,22,23,],[16,-6,-13,-14,-15,-5,-12,]),'COMMA':([11,12,13,14,18,19,20,21,23,26,27,],[17,-13,-14,-15,24,25,-7,-8,-12,-11,24,]),'RBRACKET':([18,19,20,21,26,27,],[23,-9,-7,-8,-11,-10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,],[1,]),'function_chain':([3,7,],[4,9,]),'function':([3,7,],[5,5,]),'params':([8,],[10,]),'param':([8,17,],[11,22,]),'list':([8,17,],[12,12,]),'list_elements':([15,25,],[18,27,]),'atom':([15,24,25,],[19,26,19,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> VAR DOT function_chain','expression',3,'p_expression_start','calcYacc.py',15),
  ('function_chain -> function','function_chain',1,'p_function_chain','calcYacc.py',20),
  ('function_chain -> function DOT function_chain','function_chain',3,'p_function_chain','calcYacc.py',21),
  ('function -> FUNCTION LPAREN params RPAREN','function',4,'p_function','calcYacc.py',29),
  ('params -> param COMMA param','params',3,'p_params','calcYacc.py',36),
  ('params -> param','params',1,'p_params','calcYacc.py',37),
  ('atom -> STRING','atom',1,'p_atom','calcYacc.py',49),
  ('atom -> NUMBER','atom',1,'p_atom','calcYacc.py',50),
  ('list_elements -> atom','list_elements',1,'p_list_elements','calcYacc.py',56),
  ('list_elements -> atom COMMA list_elements','list_elements',3,'p_list_elements','calcYacc.py',57),
  ('list_elements -> list_elements COMMA atom','list_elements',3,'p_list_elements','calcYacc.py',58),
  ('list -> LBRACKET list_elements RBRACKET','list',3,'p_list','calcYacc.py',72),
  ('param -> list','param',1,'p_param','calcYacc.py',77),
  ('param -> STRING','param',1,'p_param','calcYacc.py',78),
  ('param -> NUMBER','param',1,'p_param','calcYacc.py',79),
]
